name: Deploy Development_test to GCP instance
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.1.0
        with:
          project_id: greatergoods
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Deploy dev code to VM instance
        uses: google-github-actions/gcloud@master
        with:
          args: compute ssh leticiaemarcos200001@app-server-instance-dev --command 'cd /home/leticiaemarcos200001/Projeto_Final_LTI && git pull origin dev && git checkout dev'
