name: Deploy Production to GCP (multiple VMs)  Ubuntu LTS instances
on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: deploy to host-1
        uses: appleboy/ssh-action@master
        with:
          host: "34.155.6.254"
          username: leticiaemarcos200001
          key: ${{ secrets.HOST_1_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/leticiaemarcos200001/Projeto_Final_LTI
            git stash
            git config pull.rebase false
            git checkout prod
            git pull origin prod
            mv client/.env.prod client/.env
            mv server/.env.prod server/.env
            mv docker-compose.prod.yaml docker-compose.yaml 
            cd client
            yarn install
            cd ..
            cd server
            npm install
            cd ..
            sudo docker compose up -d --build
      
      - name: deploy to host-2
        uses: appleboy/ssh-action@master
        with:
          host: "34.163.4.70"
          username: leticiaemarcos200001
          key: ${{ secrets.HOST_2_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/leticiaemarcos200001/Projeto_Final_LTI
            git stash
            git config pull.rebase false
            git checkout prod
            git pull origin prod
            mv client/.env.prod client/.env
            mv server/.env.prod server/.env
            mv docker-compose.prod.yaml docker-compose.yaml 
            cd client
            yarn install
            cd ..
            cd server
            npm install
            cd ..
            sudo docker compose up -d --build

      - name: deploy to host-3
        uses: appleboy/ssh-action@master
        with:
          host: "34.163.39.159"
          username: leticiaemarcos200001
          key: ${{ secrets.HOST_3_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/leticiaemarcos200001/Projeto_Final_LTI
            git stash
            git config pull.rebase false
            git checkout prod
            git pull origin prod
            mv client/.env.prod client/.env
            mv server/.env.prod server/.env
            mv docker-compose.prod.yaml docker-compose.yaml 
            cd client
            yarn install
            cd ..
            cd server
            npm install
            cd ..
            sudo docker compose up -d --build